### ISSUE TITLE
Display error when searching directories

### ISSUE THREAD

**Issue by arkhan** [laloch/xontrib-fzf-widgets#2]
Greetings, great work.

It works wonderfully, but when trying to find Files or Directories it tries to show the colors, and this gives a bad display of the directory name, this can be seen in the attached image

![img-2020-06-04-214250](https://user-images.githubusercontent.com/3141865/83831546-42e3cd80-a6ad-11ea-8854-579edf5ef868.png)

Thanks

**Comment by laloch** [comment]
Hi @arkhan, thanks for reporting!
What are your `$fzf_find_command` and `$FZF_DEFAULT_COMMAND`?

**Comment by laloch** [comment]
See https://github.com/laloch/xontrib-fzf-widgets/blob/master/README.rst#troubleshooting for explanation.

**Comment by arkhan** [comment]
> Hi @arkhan, thanks for reporting!
> What are your `$fzf_find_command` and `$FZF_DEFAULT_COMMAND`?
I have this:

![img-2020-06-05-090739](https://user-images.githubusercontent.com/3141865/83885567-232fc200-a70c-11ea-93dd-38a0eb47155a.png)

and not set $FZF_DEFAULT_COMMAND

Thanks

**Comment by laloch** [comment]
OK, that's strange, because `fd` should by default (it does for me) recognize, that its output is being piped to `fzf` and turn the coloring off. However, you have two options:

1. Turn the colors off by setting
```
$fzf_find_command = "fd --color never"
$fzf_find_dirs_command = "fd --color never -t d"
```
2. Make `fzf` use the colored output by appending `--ansi` argument to `$FZF_DEFAULT_OPTS`. I, for instance, have
```
$FZF_DEFAULT_OPTS = "--tiebreak=index --ansi --border"
```

**Comment by arkhan** [comment]
Great, thank you very much now it works perfectly
